<?php

$registro['idPregunta1'] ='Un medio ambiente limpio es fuente de satisfacción';
$registro['idPregunta2'] ='Cuidar el medio ambiente es cuidarnos a nosotros mismos, uno no está separado del otro';
$registro['idPregunta3'] ='Ahorrar recursos con los que tengas contacto diario';
$registro['idPregunta4'] ='Reciclaje de papel, Reciclaje de vidrio';
$registro['idPregunta5'] ='Reducir los envases o productos de usar y tirar';
$registro['idPregunta6'] ='Compra solo lo que necesitas';
$registro['idPregunta7'] ='Las pérdidas de alimentos conllevan el desperdicio de recursos utilizados en la producción como tierra, agua, energía e insumos';
$registro['idPregunta8'] ='Los voluntarios se encargan de recoger todos los residuos que puedan de las playas y, de ser posible, identificarlos para que estos sean reciclados';

$registroJson = json_encode($registro);
echo $registroJson
?>