"""empty message

Revision ID: 4ba0980e3903
Revises: 
Create Date: 2023-03-31 21:59:53.613105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba0980e3903'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cemento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Marca', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cheetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=255), nullable=True),
    sa.Column('Precio', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dulces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=255), nullable=True),
    sa.Column('Precio', sa.String(length=255), nullable=True),
    sa.Column('Marca', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dulces')
    op.drop_table('cheetos')
    op.drop_table('cemento')
    # ### end Alembic commands ###
